Fix: Chalice overrides Azul ChaliceApp
DataBiosphere/azul-chalice pull request #1
Opened 2020-08-05 21:49 UTC by achave11

*Issue [Azul #2112](https://github.com/DataBiosphere/azul/issues/2112)

*Description of changes:*
Prevent `LocalChalice` from overriding Azul Chalice app, instead inject it as a super class.

2020-08-06 17:48 UTC, jessebrennan approved these changes
We talked about this on the phone. It seems reasonable, but it would definitely be helpful to link to the Stackoverflow post of whatever it was that gave you this idea, along with an explanation of why this is necessary.

I'll leave this up to your and @hannes-ucsc's discretion though.

2020-08-06 20:08 UTC, hannes-ucsc requested changes

2020-08-06 20:08 UTC, hannes-ucsc commented on chalice/local.py
> +    # Inject incoming class into LocalChalice class https://stackoverflow.com/a/11050571/7830612
```suggestion
    # Inject LocalChalice as a super-class of the class that the app object is an instance of. We do this so we 
    # can override the `current_request` property setters and getters.
    # (based on https://stackoverflow.com/a/11050571/7830612)
```

2020-08-11 20:20 UTC, hannes-ucsc approved these changes

2020-08-11 20:34 UTC, merged