Use TF reference for aws_lambda_permission
DataBiosphere/azul-chalice pull request #7
Opened 2021-05-12 22:48 UTC by jessebrennan

This was accidentally omitted from 36de57ddd5753ae5ee97fd59cc8bd951cb4ac2ce and caused https://github.com/DataBiosphere/azul/issues/1672 to crop up again.

2021-05-12 23:41 UTC, jessebrennan commented
This is a multipart change. First comes the change to azul-chalice, here. Once approved, I will make a new release of azul-chalice. Finally there will be a change to update requirements in Azul to use the new version.

2021-05-13 04:37 UTC, noah-aviel-dove approved these changes

2021-05-21 01:10 UTC, hannes-ucsc approved these changes

2021-05-21 01:12 UTC, hannes-ucsc commented
It would have helped to name the branch according to the established scheme. Please be more cognizant of existing conventions.

2021-05-21 01:17 UTC, hannes-ucsc requested changes
In fact, I think I described what I expect in sufficient detail on Slack.

https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1620432210461900?thread_ts=1620427731.461000&cid=C705Y6G9Z

You will need to do a new PR.

2021-05-21 01:17 UTC, closed without merging

2021-05-21 18:28 UTC, hannes-ucsc commented
Ignore the above comments, I got confused by your #6 attempt and the push of the tag.

I still need a new PR that's not from a fork. And please confirm that you deleted the tag you pushed by mistake as part of #6.

2021-05-28 01:20 UTC, jessebrennan commented
>And please confirm that you deleted the tag you pushed by mistake as part of #6.

The tag I had pushed before and deleted was `1.22.4+5`

To prove the tag is deleted:

```
(.venv) jesse@vader ~/gi/chalice (issues/jesse/tf-refs)$ git fetch azul-chalice 
(.venv) jesse@vader ~/gi/chalice (issues/jesse/tf-refs)$ git ls-remote azul-chalice | grep +5
66762ff24abc548419b4455c1d00a452fe0ead33        refs/tags/1.14.0+5
23ae31b5e0b6385b2c9e01ed0d9095a7c9161a42        refs/tags/1.18.0+5
```